version: '1'

services:
  server:
    build: .
    volumes:
      - data:/opt/minecraft
    ports:
      - "25565:25565"
    environment:
      - EULA=true
      - MOTD=A\ Minecraft\ Server
      #- JAVA_HEAP_MIN=2G
      #- JAVA_HEAP_MAX=2G
      #- DELETE_WORLD=false
      #- ALLOW_FLIGHT=false
      #- ALLOW_NETHER=true
      #- DIFFICULTY=normal
      #- ENABLE_COMMAND_BLOCK=false
      #- ENFORCE_SECURE_PROFILE=true
      #- ENFORCE_WHITELIST=true
      #- GAMEMODE=survival
      #- GENERATE_STRUCTURES=true
      #- HARDCORE=false
      #- LEVEL_SEED=
      #- MAX_PLAYERS=5
      #- ONLINE_MODE=true
      #- PVP=true
      #- SERVER_IP=
      #- SERVER_PORT=25565
      #- SIMULATION_DISTANCE=16
      #- SPAWN_ANIMALS=true
      #- SPAWN_MONSTERS=true
      #- SPAWN_NPCS=true
      #- SPAWN_PROTECTION=0
      #- VIEW_DISTANCE=16
      - WHITE_LIST=true
      - ADMIN=1lucas_

volumes:
  data: