version: '3'

services:
  server:
    build: .
    restart: unless-stopped
    volumes:
      - data:/opt/minecraft
    ports:
      - "25565:25565"
    environment:
      - EULA=true
      - MOTD=A\ Minecraft\ Server
      - JAVA_HEAP_MIN=1G
      - JAVA_HEAP_MAX=6G
      - MAX_PLAYERS=5
      - SPAWN_PROTECTION=0
      - WHITE_LIST=true
      - ADMIN=1lucas_
      #- ALLOW_FLIGHT=false
      #- ALLOW_NETHER=true
      #- DIFFICULTY=normal
      #- ENABLE_COMMAND_BLOCK=false
      #- ENFORCE_SECURE_PROFILE=true
      #- ENFORCE_WHITELIST=true
      #- GAMEMODE=survival
      #- GENERATE_STRUCTURES=true
      #- HARDCORE=false
      #- LEVEL_SEED=
      #- ONLINE_MODE=true
      #- PVP=true
      #- SERVER_IP=
      #- SIMULATION_DISTANCE=16
      #- SPAWN_ANIMALS=true
      #- SPAWN_MONSTERS=true
      #- SPAWN_NPCS=true
      #- VIEW_DISTANCE=16

volumes:
  data: